// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: worker/func/shared/process_rpc_proto.proto

package process_rpc_proto;

public final class ProcessRpcProto {
  private ProcessRpcProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FuncStartedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process_rpc_proto.FuncStarted)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string fnid = 1;</code>
     */
    boolean hasFnid();
    /**
     * <code>required string fnid = 1;</code>
     */
    java.lang.String getFnid();
    /**
     * <code>required string fnid = 1;</code>
     */
    com.google.protobuf.ByteString
        getFnidBytes();

    /**
     * <code>optional string http_port = 2;</code>
     */
    boolean hasHttpPort();
    /**
     * <code>optional string http_port = 2;</code>
     */
    java.lang.String getHttpPort();
    /**
     * <code>optional string http_port = 2;</code>
     */
    com.google.protobuf.ByteString
        getHttpPortBytes();
  }
  /**
   * <pre>
   * Sample message.
   * </pre>
   *
   * Protobuf type {@code process_rpc_proto.FuncStarted}
   */
  public  static final class FuncStarted extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:process_rpc_proto.FuncStarted)
      FuncStartedOrBuilder {
    // Use FuncStarted.newBuilder() to construct.
    private FuncStarted(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FuncStarted() {
      fnid_ = "";
      httpPort_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FuncStarted(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              fnid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              httpPort_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncStarted_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncStarted_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              process_rpc_proto.ProcessRpcProto.FuncStarted.class, process_rpc_proto.ProcessRpcProto.FuncStarted.Builder.class);
    }

    private int bitField0_;
    public static final int FNID_FIELD_NUMBER = 1;
    private volatile java.lang.Object fnid_;
    /**
     * <code>required string fnid = 1;</code>
     */
    public boolean hasFnid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string fnid = 1;</code>
     */
    public java.lang.String getFnid() {
      java.lang.Object ref = fnid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fnid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string fnid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFnidBytes() {
      java.lang.Object ref = fnid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fnid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HTTP_PORT_FIELD_NUMBER = 2;
    private volatile java.lang.Object httpPort_;
    /**
     * <code>optional string http_port = 2;</code>
     */
    public boolean hasHttpPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string http_port = 2;</code>
     */
    public java.lang.String getHttpPort() {
      java.lang.Object ref = httpPort_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          httpPort_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string http_port = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHttpPortBytes() {
      java.lang.Object ref = httpPort_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpPort_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFnid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fnid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, httpPort_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fnid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, httpPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof process_rpc_proto.ProcessRpcProto.FuncStarted)) {
        return super.equals(obj);
      }
      process_rpc_proto.ProcessRpcProto.FuncStarted other = (process_rpc_proto.ProcessRpcProto.FuncStarted) obj;

      boolean result = true;
      result = result && (hasFnid() == other.hasFnid());
      if (hasFnid()) {
        result = result && getFnid()
            .equals(other.getFnid());
      }
      result = result && (hasHttpPort() == other.hasHttpPort());
      if (hasHttpPort()) {
        result = result && getHttpPort()
            .equals(other.getHttpPort());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFnid()) {
        hash = (37 * hash) + FNID_FIELD_NUMBER;
        hash = (53 * hash) + getFnid().hashCode();
      }
      if (hasHttpPort()) {
        hash = (37 * hash) + HTTP_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getHttpPort().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static process_rpc_proto.ProcessRpcProto.FuncStarted parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncStarted parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncStarted parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncStarted parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncStarted parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncStarted parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncStarted parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncStarted parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncStarted parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncStarted parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(process_rpc_proto.ProcessRpcProto.FuncStarted prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Sample message.
     * </pre>
     *
     * Protobuf type {@code process_rpc_proto.FuncStarted}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process_rpc_proto.FuncStarted)
        process_rpc_proto.ProcessRpcProto.FuncStartedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncStarted_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncStarted_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                process_rpc_proto.ProcessRpcProto.FuncStarted.class, process_rpc_proto.ProcessRpcProto.FuncStarted.Builder.class);
      }

      // Construct using process_rpc_proto.ProcessRpcProto.FuncStarted.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        fnid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        httpPort_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncStarted_descriptor;
      }

      public process_rpc_proto.ProcessRpcProto.FuncStarted getDefaultInstanceForType() {
        return process_rpc_proto.ProcessRpcProto.FuncStarted.getDefaultInstance();
      }

      public process_rpc_proto.ProcessRpcProto.FuncStarted build() {
        process_rpc_proto.ProcessRpcProto.FuncStarted result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public process_rpc_proto.ProcessRpcProto.FuncStarted buildPartial() {
        process_rpc_proto.ProcessRpcProto.FuncStarted result = new process_rpc_proto.ProcessRpcProto.FuncStarted(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fnid_ = fnid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.httpPort_ = httpPort_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof process_rpc_proto.ProcessRpcProto.FuncStarted) {
          return mergeFrom((process_rpc_proto.ProcessRpcProto.FuncStarted)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(process_rpc_proto.ProcessRpcProto.FuncStarted other) {
        if (other == process_rpc_proto.ProcessRpcProto.FuncStarted.getDefaultInstance()) return this;
        if (other.hasFnid()) {
          bitField0_ |= 0x00000001;
          fnid_ = other.fnid_;
          onChanged();
        }
        if (other.hasHttpPort()) {
          bitField0_ |= 0x00000002;
          httpPort_ = other.httpPort_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFnid()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        process_rpc_proto.ProcessRpcProto.FuncStarted parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (process_rpc_proto.ProcessRpcProto.FuncStarted) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object fnid_ = "";
      /**
       * <code>required string fnid = 1;</code>
       */
      public boolean hasFnid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fnid = 1;</code>
       */
      public java.lang.String getFnid() {
        java.lang.Object ref = fnid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fnid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string fnid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFnidBytes() {
        java.lang.Object ref = fnid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fnid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string fnid = 1;</code>
       */
      public Builder setFnid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fnid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string fnid = 1;</code>
       */
      public Builder clearFnid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fnid_ = getDefaultInstance().getFnid();
        onChanged();
        return this;
      }
      /**
       * <code>required string fnid = 1;</code>
       */
      public Builder setFnidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        fnid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object httpPort_ = "";
      /**
       * <code>optional string http_port = 2;</code>
       */
      public boolean hasHttpPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string http_port = 2;</code>
       */
      public java.lang.String getHttpPort() {
        java.lang.Object ref = httpPort_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            httpPort_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string http_port = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHttpPortBytes() {
        java.lang.Object ref = httpPort_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          httpPort_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string http_port = 2;</code>
       */
      public Builder setHttpPort(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        httpPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string http_port = 2;</code>
       */
      public Builder clearHttpPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        httpPort_ = getDefaultInstance().getHttpPort();
        onChanged();
        return this;
      }
      /**
       * <code>optional string http_port = 2;</code>
       */
      public Builder setHttpPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        httpPort_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:process_rpc_proto.FuncStarted)
    }

    // @@protoc_insertion_point(class_scope:process_rpc_proto.FuncStarted)
    private static final process_rpc_proto.ProcessRpcProto.FuncStarted DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new process_rpc_proto.ProcessRpcProto.FuncStarted();
    }

    public static process_rpc_proto.ProcessRpcProto.FuncStarted getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FuncStarted>
        PARSER = new com.google.protobuf.AbstractParser<FuncStarted>() {
      public FuncStarted parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FuncStarted(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FuncStarted> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FuncStarted> getParserForType() {
      return PARSER;
    }

    public process_rpc_proto.ProcessRpcProto.FuncStarted getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FuncCallReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process_rpc_proto.FuncCallReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string func = 1;</code>
     */
    boolean hasFunc();
    /**
     * <code>required string func = 1;</code>
     */
    java.lang.String getFunc();
    /**
     * <code>required string func = 1;</code>
     */
    com.google.protobuf.ByteString
        getFuncBytes();

    /**
     * <code>required string arg_str = 2;</code>
     */
    boolean hasArgStr();
    /**
     * <code>required string arg_str = 2;</code>
     */
    java.lang.String getArgStr();
    /**
     * <code>required string arg_str = 2;</code>
     */
    com.google.protobuf.ByteString
        getArgStrBytes();
  }
  /**
   * Protobuf type {@code process_rpc_proto.FuncCallReq}
   */
  public  static final class FuncCallReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:process_rpc_proto.FuncCallReq)
      FuncCallReqOrBuilder {
    // Use FuncCallReq.newBuilder() to construct.
    private FuncCallReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FuncCallReq() {
      func_ = "";
      argStr_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FuncCallReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              func_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              argStr_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncCallReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncCallReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              process_rpc_proto.ProcessRpcProto.FuncCallReq.class, process_rpc_proto.ProcessRpcProto.FuncCallReq.Builder.class);
    }

    private int bitField0_;
    public static final int FUNC_FIELD_NUMBER = 1;
    private volatile java.lang.Object func_;
    /**
     * <code>required string func = 1;</code>
     */
    public boolean hasFunc() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string func = 1;</code>
     */
    public java.lang.String getFunc() {
      java.lang.Object ref = func_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          func_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string func = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFuncBytes() {
      java.lang.Object ref = func_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        func_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARG_STR_FIELD_NUMBER = 2;
    private volatile java.lang.Object argStr_;
    /**
     * <code>required string arg_str = 2;</code>
     */
    public boolean hasArgStr() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string arg_str = 2;</code>
     */
    public java.lang.String getArgStr() {
      java.lang.Object ref = argStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          argStr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string arg_str = 2;</code>
     */
    public com.google.protobuf.ByteString
        getArgStrBytes() {
      java.lang.Object ref = argStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        argStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasFunc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArgStr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, func_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, argStr_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, func_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, argStr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof process_rpc_proto.ProcessRpcProto.FuncCallReq)) {
        return super.equals(obj);
      }
      process_rpc_proto.ProcessRpcProto.FuncCallReq other = (process_rpc_proto.ProcessRpcProto.FuncCallReq) obj;

      boolean result = true;
      result = result && (hasFunc() == other.hasFunc());
      if (hasFunc()) {
        result = result && getFunc()
            .equals(other.getFunc());
      }
      result = result && (hasArgStr() == other.hasArgStr());
      if (hasArgStr()) {
        result = result && getArgStr()
            .equals(other.getArgStr());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasFunc()) {
        hash = (37 * hash) + FUNC_FIELD_NUMBER;
        hash = (53 * hash) + getFunc().hashCode();
      }
      if (hasArgStr()) {
        hash = (37 * hash) + ARG_STR_FIELD_NUMBER;
        hash = (53 * hash) + getArgStr().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static process_rpc_proto.ProcessRpcProto.FuncCallReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(process_rpc_proto.ProcessRpcProto.FuncCallReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code process_rpc_proto.FuncCallReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process_rpc_proto.FuncCallReq)
        process_rpc_proto.ProcessRpcProto.FuncCallReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncCallReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncCallReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                process_rpc_proto.ProcessRpcProto.FuncCallReq.class, process_rpc_proto.ProcessRpcProto.FuncCallReq.Builder.class);
      }

      // Construct using process_rpc_proto.ProcessRpcProto.FuncCallReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        func_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        argStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncCallReq_descriptor;
      }

      public process_rpc_proto.ProcessRpcProto.FuncCallReq getDefaultInstanceForType() {
        return process_rpc_proto.ProcessRpcProto.FuncCallReq.getDefaultInstance();
      }

      public process_rpc_proto.ProcessRpcProto.FuncCallReq build() {
        process_rpc_proto.ProcessRpcProto.FuncCallReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public process_rpc_proto.ProcessRpcProto.FuncCallReq buildPartial() {
        process_rpc_proto.ProcessRpcProto.FuncCallReq result = new process_rpc_proto.ProcessRpcProto.FuncCallReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.func_ = func_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.argStr_ = argStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof process_rpc_proto.ProcessRpcProto.FuncCallReq) {
          return mergeFrom((process_rpc_proto.ProcessRpcProto.FuncCallReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(process_rpc_proto.ProcessRpcProto.FuncCallReq other) {
        if (other == process_rpc_proto.ProcessRpcProto.FuncCallReq.getDefaultInstance()) return this;
        if (other.hasFunc()) {
          bitField0_ |= 0x00000001;
          func_ = other.func_;
          onChanged();
        }
        if (other.hasArgStr()) {
          bitField0_ |= 0x00000002;
          argStr_ = other.argStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFunc()) {
          return false;
        }
        if (!hasArgStr()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        process_rpc_proto.ProcessRpcProto.FuncCallReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (process_rpc_proto.ProcessRpcProto.FuncCallReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object func_ = "";
      /**
       * <code>required string func = 1;</code>
       */
      public boolean hasFunc() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string func = 1;</code>
       */
      public java.lang.String getFunc() {
        java.lang.Object ref = func_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            func_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string func = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFuncBytes() {
        java.lang.Object ref = func_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          func_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string func = 1;</code>
       */
      public Builder setFunc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        func_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string func = 1;</code>
       */
      public Builder clearFunc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        func_ = getDefaultInstance().getFunc();
        onChanged();
        return this;
      }
      /**
       * <code>required string func = 1;</code>
       */
      public Builder setFuncBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        func_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object argStr_ = "";
      /**
       * <code>required string arg_str = 2;</code>
       */
      public boolean hasArgStr() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string arg_str = 2;</code>
       */
      public java.lang.String getArgStr() {
        java.lang.Object ref = argStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            argStr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string arg_str = 2;</code>
       */
      public com.google.protobuf.ByteString
          getArgStrBytes() {
        java.lang.Object ref = argStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          argStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string arg_str = 2;</code>
       */
      public Builder setArgStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        argStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string arg_str = 2;</code>
       */
      public Builder clearArgStr() {
        bitField0_ = (bitField0_ & ~0x00000002);
        argStr_ = getDefaultInstance().getArgStr();
        onChanged();
        return this;
      }
      /**
       * <code>required string arg_str = 2;</code>
       */
      public Builder setArgStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        argStr_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:process_rpc_proto.FuncCallReq)
    }

    // @@protoc_insertion_point(class_scope:process_rpc_proto.FuncCallReq)
    private static final process_rpc_proto.ProcessRpcProto.FuncCallReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new process_rpc_proto.ProcessRpcProto.FuncCallReq();
    }

    public static process_rpc_proto.ProcessRpcProto.FuncCallReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FuncCallReq>
        PARSER = new com.google.protobuf.AbstractParser<FuncCallReq>() {
      public FuncCallReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FuncCallReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FuncCallReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FuncCallReq> getParserForType() {
      return PARSER;
    }

    public process_rpc_proto.ProcessRpcProto.FuncCallReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FuncCallRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process_rpc_proto.FuncCallResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ret_str = 1;</code>
     */
    boolean hasRetStr();
    /**
     * <code>required string ret_str = 1;</code>
     */
    java.lang.String getRetStr();
    /**
     * <code>required string ret_str = 1;</code>
     */
    com.google.protobuf.ByteString
        getRetStrBytes();
  }
  /**
   * Protobuf type {@code process_rpc_proto.FuncCallResp}
   */
  public  static final class FuncCallResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:process_rpc_proto.FuncCallResp)
      FuncCallRespOrBuilder {
    // Use FuncCallResp.newBuilder() to construct.
    private FuncCallResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FuncCallResp() {
      retStr_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FuncCallResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              retStr_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncCallResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncCallResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              process_rpc_proto.ProcessRpcProto.FuncCallResp.class, process_rpc_proto.ProcessRpcProto.FuncCallResp.Builder.class);
    }

    private int bitField0_;
    public static final int RET_STR_FIELD_NUMBER = 1;
    private volatile java.lang.Object retStr_;
    /**
     * <code>required string ret_str = 1;</code>
     */
    public boolean hasRetStr() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ret_str = 1;</code>
     */
    public java.lang.String getRetStr() {
      java.lang.Object ref = retStr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retStr_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ret_str = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRetStrBytes() {
      java.lang.Object ref = retStr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retStr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetStr()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, retStr_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, retStr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof process_rpc_proto.ProcessRpcProto.FuncCallResp)) {
        return super.equals(obj);
      }
      process_rpc_proto.ProcessRpcProto.FuncCallResp other = (process_rpc_proto.ProcessRpcProto.FuncCallResp) obj;

      boolean result = true;
      result = result && (hasRetStr() == other.hasRetStr());
      if (hasRetStr()) {
        result = result && getRetStr()
            .equals(other.getRetStr());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasRetStr()) {
        hash = (37 * hash) + RET_STR_FIELD_NUMBER;
        hash = (53 * hash) + getRetStr().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static process_rpc_proto.ProcessRpcProto.FuncCallResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static process_rpc_proto.ProcessRpcProto.FuncCallResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(process_rpc_proto.ProcessRpcProto.FuncCallResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code process_rpc_proto.FuncCallResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process_rpc_proto.FuncCallResp)
        process_rpc_proto.ProcessRpcProto.FuncCallRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncCallResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncCallResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                process_rpc_proto.ProcessRpcProto.FuncCallResp.class, process_rpc_proto.ProcessRpcProto.FuncCallResp.Builder.class);
      }

      // Construct using process_rpc_proto.ProcessRpcProto.FuncCallResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        retStr_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return process_rpc_proto.ProcessRpcProto.internal_static_process_rpc_proto_FuncCallResp_descriptor;
      }

      public process_rpc_proto.ProcessRpcProto.FuncCallResp getDefaultInstanceForType() {
        return process_rpc_proto.ProcessRpcProto.FuncCallResp.getDefaultInstance();
      }

      public process_rpc_proto.ProcessRpcProto.FuncCallResp build() {
        process_rpc_proto.ProcessRpcProto.FuncCallResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public process_rpc_proto.ProcessRpcProto.FuncCallResp buildPartial() {
        process_rpc_proto.ProcessRpcProto.FuncCallResp result = new process_rpc_proto.ProcessRpcProto.FuncCallResp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retStr_ = retStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof process_rpc_proto.ProcessRpcProto.FuncCallResp) {
          return mergeFrom((process_rpc_proto.ProcessRpcProto.FuncCallResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(process_rpc_proto.ProcessRpcProto.FuncCallResp other) {
        if (other == process_rpc_proto.ProcessRpcProto.FuncCallResp.getDefaultInstance()) return this;
        if (other.hasRetStr()) {
          bitField0_ |= 0x00000001;
          retStr_ = other.retStr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRetStr()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        process_rpc_proto.ProcessRpcProto.FuncCallResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (process_rpc_proto.ProcessRpcProto.FuncCallResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object retStr_ = "";
      /**
       * <code>required string ret_str = 1;</code>
       */
      public boolean hasRetStr() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string ret_str = 1;</code>
       */
      public java.lang.String getRetStr() {
        java.lang.Object ref = retStr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retStr_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ret_str = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRetStrBytes() {
        java.lang.Object ref = retStr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retStr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ret_str = 1;</code>
       */
      public Builder setRetStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        retStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string ret_str = 1;</code>
       */
      public Builder clearRetStr() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retStr_ = getDefaultInstance().getRetStr();
        onChanged();
        return this;
      }
      /**
       * <code>required string ret_str = 1;</code>
       */
      public Builder setRetStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        retStr_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:process_rpc_proto.FuncCallResp)
    }

    // @@protoc_insertion_point(class_scope:process_rpc_proto.FuncCallResp)
    private static final process_rpc_proto.ProcessRpcProto.FuncCallResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new process_rpc_proto.ProcessRpcProto.FuncCallResp();
    }

    public static process_rpc_proto.ProcessRpcProto.FuncCallResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FuncCallResp>
        PARSER = new com.google.protobuf.AbstractParser<FuncCallResp>() {
      public FuncCallResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FuncCallResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FuncCallResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FuncCallResp> getParserForType() {
      return PARSER;
    }

    public process_rpc_proto.ProcessRpcProto.FuncCallResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_process_rpc_proto_FuncStarted_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_process_rpc_proto_FuncStarted_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_process_rpc_proto_FuncCallReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_process_rpc_proto_FuncCallReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_process_rpc_proto_FuncCallResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_process_rpc_proto_FuncCallResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*worker/func/shared/process_rpc_proto.p" +
      "roto\022\021process_rpc_proto\".\n\013FuncStarted\022\014" +
      "\n\004fnid\030\001 \002(\t\022\021\n\thttp_port\030\002 \001(\t\",\n\013FuncC" +
      "allReq\022\014\n\004func\030\001 \002(\t\022\017\n\007arg_str\030\002 \002(\t\"\037\n" +
      "\014FuncCallResp\022\017\n\007ret_str\030\001 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_process_rpc_proto_FuncStarted_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_process_rpc_proto_FuncStarted_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_process_rpc_proto_FuncStarted_descriptor,
        new java.lang.String[] { "Fnid", "HttpPort", });
    internal_static_process_rpc_proto_FuncCallReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_process_rpc_proto_FuncCallReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_process_rpc_proto_FuncCallReq_descriptor,
        new java.lang.String[] { "Func", "ArgStr", });
    internal_static_process_rpc_proto_FuncCallResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_process_rpc_proto_FuncCallResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_process_rpc_proto_FuncCallResp_descriptor,
        new java.lang.String[] { "RetStr", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
