comment: 非常方便磁盘使用分析工具

prepare:
  # x86
  - url: https://dev.yorhel.nl/download/ncdu-2.5-linux-x86_64.tar.gz
    as: ncdu-2.5-linux-x86_64.tar.gz
    trans:
      - extract
      - copy:
          - ncdu: teledeploy/ncdu_amd64
  # arm
  - url: https://dev.yorhel.nl/download/ncdu-2.5-linux-aarch64.tar.gz
    as: ncdu-2.5-linux-aarch64.tar.gz
    trans:
      - extract
      - copy:
          - ncdu: teledeploy/ncdu_arm64

bin:
  waverless:
